name: Documentation CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  TZ: Asia/Shanghai

jobs:
  build-and-deply:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -U sphinx
          pip install -U sphinx-rtd-theme
          
      - name: Build sphinx
        run: |
          make html
     
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _build/html
          CLEAN: true
